name: Nightly
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "LICENSE-*"
      - ".gitignore"
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: RUST_TEST_THREADS=1 cargo test --all-features
